version: '3.8'
services:
  mysql:
    image: mysql:5.7.31
    volumes:
      - ${HOME}/.docker_data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
